= YAPBENZET

== Kocaeli University Computer Engineering Department

_Gurkan Gokdemir <https://github.com/gurkangokdemir[gurkangokdemir@outlook.com]>_

== Abstract

_This is a project that contains 4 x 4 blocks YAPBENZET. User can easily upload their picture to the application._

Major funding for *YAPBENZET*
 is provided by our *YAPBENZET*, 

== The Big Picture

*YAPBENZET*
 reads content written in plain text, as shown in the panel on the left in the image below, and converts it to HTML5, as shown rendered in the right panel.
*YAPBENZET*
 applies a default stylesheet to the HTML5 document to provide a pleasant out-of-the-box experience.

== AsciiDoc Processing

*YAPBENZET*
 reads and parses text written in the AsciiDoc syntax, then feeds the parse tree to a set of built-in converters to produce HTML5, DocBook 5, and man(ual) page output.
You have the option of using your own converter or loading supported templates to customize the generated output or produce additional formats.

*YAPBENZET*
 is a drop-in replacement for the original AsciiDoc Python processor (`YAPBENZET.exe`).
The *YAPBENZET*
 test suite has {uri-tests}[> 2,000 tests] to ensure compatibility with the AsciiDoc syntax.

In addition to the classic AsciiDoc syntax, *YAPBENZET*
 recognizes additional markup and formatting options, such as font-based icons and UI elements.
*YAPBENZET*
 also offers a modern, responsive theme based on {uri-foundation}[Foundation] to style the HTML5 output.

== Requirements

*YAPBENZET*
 works on Windows and requires one of the following implementations of 

* Visual Studio 
* C# Packages

[CAUTION]
====
After the instaliation you can detect some bugs on the project. That project is the first version. 
====

== Installation

*YAPBENZET*
 can be installed using (a) package managers for popular Linux distributions, (b) Homebrew for macOS, (c) the `apt-get install` command (recommended for Windows users), (d) the *YAPBENZET*
 Docker image, or (e) Bundler.

The benefit of using your operating system's package manager to install the gem is that it handles installing library if those packages are not already installed on your machine.

=== (a) Linux package managers

The version of *YAPBENZET*
 installed by the package manager may not match the latest release of *YAPBENZET*
.
Consult the package repository for your distribution to find out which version is packaged per distribution release.

* https://github.com/gurkangokdemir/packages?name=YAPBENZET
[Gurkan Gokdemir (*YAPBENZET*)]


If you want to use a version of *YAPBENZET*
 that is newer than what is installed by the package manager, see the <<apt-get install,installation instructions>>.

==== apk (Kocaeli University)

To install the apk on Kocaeli University, open a terminal and type:

 $ sudo apk add YAPBENZET


== Upgrade

If you installed *YAPBENZET*
 using a package manager, your operating system is probably configured to automatically update packages, in which case you don't need to update the apk manually.

=== apk (Kocaeli University)

To upgrade the apk, use:

 $ sudo apk add -u YAPBENZET

== Usage

If the *YAPBENZET*
 gem installed successfully, the `YAPBENZET` command line interface (CLI) will be available on your PATH.
To verify it's available, run the following in your terminal:

 $ *YAPBENZET*
  --version

=== Command line interface (CLI)

The `YAPBENZET` command allows you to invoke *YAPBENZET*
 from the command line (i.e., a terminal).

The following command converts the file README.adoc to HTML and saves the result to the file README.html in the same directory.
The name of the generated HTML file is derived from the source file by changing its file extension to `.html`.

 $ YAPBENZET
  README.adoc

You can control the *YAPBENZET*
 processor by adding various flags and switches, which you can learn about using:

 $ YAPBENZET
  --help

For instance, to write the file to a different directory, use:

 $ YAPBENZET
  -D output README.adoc

Refer to the following resources to learn more about how to use the `YAPBENZET` command.

== Contributing

New contributors are always welcome!
If you discover errors or omissions in the source code, documentation, or website content, please don't hesitate to submit an issue or open a pull request with a fix.

Here are some ways *you* can contribute:

* by using prerelease (alpha, beta or preview) versions
* by reporting bugs
* by suggesting new features
* by writing or editing documentation
* by writing code with tests -- _No patch is too small._
** fix typos
** add comments
** clean up inconsistent whitespace
** write tests!
* by refactoring code
* by fixing {uri-issues}[issues]
* by reviewing patches

The {uri-contribute}[Contributing] guide provides information on how to create, style, and submit issues, feature requests, code, and documentation to the *YAPBENZET*
 Project.

== Getting Help

*YAPBENZET*
 is developed to create your 4 x 4 YAPBENZETs with your pictures and play with it.
But we can't do it without your feedback!
We encourage you to ask questions and discuss any aspects of the project on the discussion list or on Twitter.

== License

Copyright (C) 2014-2019 Gurkan Gokdemir and the individual contributors to YAPBENZET
.
Use of this software is granted under the terms of the MIT License.


== Authors

*YAPBENZET* is led by https://github.com/gurkangokdemir[Gurkan Gokdemir].
The project was initiated in 2019 by https://github.com/gurkangokdemir[Gurkan Gokdemir].

*YAPBENZET* was started by Kocaeli University Engineering Faculty Computer Engineering Department and has received contributions from.

ifndef::env-site[]
== 8.References
* https://stackoverflow.com/questions/35151067/algorithm-to-compare-two-images-in-c-sharp
* https://stackoverflow.com/questions/1922040/how-to-resize-an-image-c-sharp

* https://stackoverflow.com/questions/13625891/cut-an-image-into-9-pieces-c-sharp
