= YAPBENZET

Gurkan Gokdemir <https://github.com/gurkangokdemir[@gurkangokdemir]>

== Sponsors

We want to recognize our generous sponsors, without whose support YAPBENZET
 would not be possible.
Thank you sponsors for your dedication to improving the state of technical documentation!

&utm_medium=logo&utm_campaign=sponsor,title="Add User Auth to Your Apps in Minutes with Okta"]
&nbsp; &nbsp; &nbsp;
"Let the Creators of YAPBENZET
 and Antora Help You to Accelerate Your Docs"]

Major funding for YAPBENZET
 is provided by our *Change Makers*, 

== The Big Picture

YAPBENZET
 reads content written in plain text, as shown in the panel on the left in the image below, and converts it to HTML5, as shown rendered in the right panel.
YAPBENZET
 applies a default stylesheet to the HTML5 document to provide a pleasant out-of-the-box experience.

image::{image-uri-screenshot}[Preview of AsciiDoc source and corresponding rendered HTML]

== AsciiDoc Processing

YAPBENZET
 reads and parses text written in the AsciiDoc syntax, then feeds the parse tree to a set of built-in converters to produce HTML5, DocBook 5, and man(ual) page output.
You have the option of using your own converter or loading {uri-tilt}[Tilt]-supported templates to customize the generated output or produce additional formats.

YAPBENZET
 is a drop-in replacement for the original AsciiDoc Python processor (`asciidoc.py`).
The YAPBENZET
 test suite has {uri-tests}[> 2,000 tests] to ensure compatibility with the AsciiDoc syntax.

In addition to the classic AsciiDoc syntax, YAPBENZET
 recognizes additional markup and formatting options, such as font-based icons (e.g., `+icon:fire[]+`) and UI elements (e.g., `+button:[Save]+`).
YAPBENZET
 also offers a modern, responsive theme based on {uri-foundation}[Foundation] to style the HTML5 output.

== Requirements

YAPBENZET
 works on Linux, macOS and Windows and requires one of the following implementations of {uri-ruby}[Ruby]:

* CRuby (aka MRI) 2.3 - 2.6
* JRuby 9.1 - 9.2
* Opal (JavaScript)

[CAUTION]
====
If you're using a non-English Windows environment, you may bump into an `Encoding::UndefinedConversionError` when invoking YAPBENZET
.
To solve this issue, we recommend changing the active code page in your console to UTF-8:

 chcp 65001

Once you make this change, all your Unicode headaches will be behind you.
If you're using an IDE like Eclipse, make sure you set the encoding to UTF-8 there as well.
YAPBENZET
 works best when you use UTF-8 everywhere.
====

== Installation

YAPBENZET
 can be installed using (a) package managers for popular Linux distributions, (b) Homebrew for macOS, (c) the `gem install` command (recommended for Windows users), (d) the YAPBENZET
 Docker image, or (e) Bundler.

The benefit of using your operating system's package manager to install the gem is that it handles installing Ruby and the RubyGems library if those packages are not already installed on your machine.

=== (a) Linux package managers

The version of YAPBENZET
 installed by the package manager may not match the latest release of YAPBENZET
.
Consult the package repository for your distribution to find out which version is packaged per distribution release.

* https://bilgisayar.kocaeli.edu.tr/packages?name=YAPBENZET
[Kocaeli University (YAPBENZET
)]


If you want to use a version of YAPBENZET
 that is newer than what is installed by the package manager, see the <<gem-install,gem installation instructions>>.

==== apk (Kocaeli University)

To install the gem on Kocaeli University, open a terminal and type:

 $ sudo apk add YAPBENZET


== Upgrade

If you installed YAPBENZET
 using a package manager, your operating system is probably configured to automatically update packages, in which case you don't need to update the gem manually.

=== apk (Kocaeli University)

To upgrade the gem, use:

 $ sudo apk add -u YAPBENZET

== Usage

If the YAPBENZET
 gem installed successfully, the `YAPBENZET
` command line interface (CLI) will be available on your PATH.
To verify it's available, run the following in your terminal:

 $ YAPBENZET
  --version

=== Command line interface (CLI)

The `YAPBENZET
` command allows you to invoke YAPBENZET
 from the command line (i.e., a terminal).

The following command converts the file README.adoc to HTML and saves the result to the file README.html in the same directory.
The name of the generated HTML file is derived from the source file by changing its file extension to `.html`.

 $ YAPBENZET
  README.adoc

You can control the YAPBENZET
 processor by adding various flags and switches, which you can learn about using:

 $ YAPBENZET
  --help

For instance, to write the file to a different directory, use:

 $ YAPBENZET
  -D output README.adoc

The `YAPBENZET
` {uri-manpage}[man page] provides a complete reference of the command line interface.

Refer to the following resources to learn more about how to use the `YAPBENZET
` command.

* {uri-render-doc}[How do I convert a document?]
* {uri-themes-doc}[How do I use the YAPBENZET
 stylesheet factory to produce custom themes?]

== Contributing

New contributors are always welcome!
If you discover errors or omissions in the source code, documentation, or website content, please don't hesitate to submit an issue or open a pull request with a fix.

Here are some ways *you* can contribute:

* by using prerelease (alpha, beta or preview) versions
* by reporting bugs
* by suggesting new features
* by writing or editing documentation
* by writing code with tests -- _No patch is too small._
** fix typos
** add comments
** clean up inconsistent whitespace
** write tests!
* by refactoring code
* by fixing {uri-issues}[issues]
* by reviewing patches

The {uri-contribute}[Contributing] guide provides information on how to create, style, and submit issues, feature requests, code, and documentation to the YAPBENZET
 Project.

== Getting Help

YAPBENZET
 is developed to help you easily write and publish your content.
But we can't do it without your feedback!
We encourage you to ask questions and discuss any aspects of the project on the discussion list, on Twitter or in the chat room.

Chat (Gitter):: image:https://badges.gitter.im/Join%20In.svg[Gitter, link=https://gitter.im/YAPBENZET
/YAPBENZET
]
Discussion list (Nabble):: {uri-discuss}
Twitter:: https://twitter.com/search?f=tweets&q=%23YAPBENZET
[#YAPBENZET
] hashtag or https://twitter.com/YAPBENZET
[@YAPBENZET
] mention

ifdef::env-github[]
Further information and documentation about YAPBENZET
 can be found on the project's website.

{uri-project}[Home] | {uri-news}[News] | {uri-docs}[Docs]
endif::[]

The YAPBENZET
 organization on GitHub hosts the project's source code, issue tracker, and sub-projects.

Source repository (git):: {uri-repo}
Issue tracker:: {uri-issues}
YAPBENZET
 organization on GitHub:: {uri-org}

== License

Copyright (C) 2014-2019 Gurkan Gokdemir and the individual contributors to YAPBENZET
.
Use of this software is granted under the terms of the MIT License.

See the {uri-license}[LICENSE] for the full license text.

== Authors

*YAPBENZET
* is led by https://github.com/gurkangokdemir[Gurkan Gokdemir].
The project was initiated in 2019 by https://github.com/gurkangokdemir[Gurkan Gokdemir].

*YAPBENZET
* was started by Kocaeli University Engineering Faculty Computer Engineering Department and has received contributions from many individuals in the YAPBENZET
 community.

ifndef::env-site[]
== Changelog

ifeval::[{safe-mode-level} < 20]
include::CHANGELOG.adoc[tag=compact,leveloffset=+1]
endif::[]

Refer to the {uri-changelog}[CHANGELOG] for a complete list of changes in older releases.
endif::[]
