= Gurkan Gokdemir's First Edit
Gurkan Gokdemir; 
v1.0.0, 2019-03-04
:description: This guide is a quick reference for the programmer.
:keywords: gurkan, gokdemir



Linux is the perfect os for hackers.


[NOTE]
====
I'm editting this text as an editor but I'm not sure to share.
====

toc::[]

== Paragraphs

.Normal
----
include::{includedir}/ex-text.adoc[tag=b-para]
----


.Linux 
****
See these sections in the document User Manual for more information and examples.

* Best operating system for servers.
* Open source.
* Stable
****


== Document Header

IMPORTANT: A header is optional.

CAUTION: The header may not contain blank lines and must be offset from the content by at least one blank line.

.Section anchors and links (Asciidoctor only)

`sectanchors`::
When this document attribute is set, a section icon anchor appears in front of the section title.

`sectlinks`::
When this document attribute is set, the section titles become self-links.
This enables a reader to bookmark the section.

NOTE: Section title anchors depend on the default Asciidoctor stylesheet to render properly.

== Images

Images are resolved relative to the value of the {uri-imagesdir}[imagesdir] document attribute, which is empty by default.
You are encouraged to make use of the `imagesdir` attribute to avoid hard-coding the common path to your images in every image macro.

The `imagesdir` attribute can be an absolute path, relative path, or base URL.
When the image target is a URL or absolute path, the imagesdir prefix is _not_ prepended.


TIP: Instead of declaring the `data-uri` attribute in the document, you can pass it as a command-line argument using `-a data-uri`.

== Videos

.Embedded Youtube video

TIP: You can control the video settings using {uri-video}[additional attributes and options] on the macro.

== Block Id, Role and Options

.Traditional (longhand) markup method for assigning block id and role
----
[[goals]]
[role="incremental"]
* Goal 1
* Goal 2
----

[TIP]
====
* To specify multiple roles using the shorthand syntax, separate them by dots.
* The order of `id` and `role` values in the shorthand syntax does not matter.
====

.Traditional (longhand) markup method for assigning quoted text anchor (id) and role
----
[[free_the_world]][big goal]_free the world_
----


== Comments

.Line
----
include::{includedir}/ex-comment.adoc[tag=line]
----

TIP: Single-line comments can be used to divide elements, such as two adjacent lists.

.Block
----
include::{includedir}/ex-comment.adoc[tag=bl]
----


[.result]
====
include::{includedir}/ex-section.adoc[tag=b-md]
====


